### ISSUE TITLE
while hover what type image of option that is in not show

### ISSUE THREAD

**Issue by Gamerking177** [bishalde/QR-Code-Generator#110]
https://github.com/bishalde/QR-Code-Generator/assets/130808542/f84f7670-6231-40db-9594-a4481db67412

i will add a feature like this

https://github.com/bishalde/QR-Code-Generator/assets/130808542/32e72ddf-c06d-427a-b190-a62daa0297cc

**Comment by Shubham-Zone** [comment]
@bishalde please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development
